Enhavo\Bundle\NewsletterBundle\Entity\Newsletter:
    type: entity
    table: newsletter_newsletter
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        slug:
            type: string
            length: 255
            nullable: true
            gedmo:
                slug:
                    separator: -
                    style: default
                    updatable: false
                    fields: ['subject']
        subject:
            type: string
            length: 255
            nullable: true
        state:
            type: string
            nullable: true
        template:
            type: string
            nullable: true
        startAt:
            type: datetime
            nullable: true
        finishAt:
            type: datetime
            nullable: true
        createdAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: create
    oneToOne:
        content:
            cascade: ['persist', 'refresh', 'remove']
            targetEntity: Enhavo\Bundle\BlockBundle\Model\NodeInterface

    oneToMany:
        receivers:
            cascade: ['persist', 'refresh', 'remove']
            targetEntity: Enhavo\Bundle\NewsletterBundle\Entity\Receiver
            mappedBy: newsletter
            orphanRemoval: true

    manyToMany:
        groups:
            cascade: ['persist', 'refresh']
            targetEntity: Enhavo\Bundle\NewsletterBundle\Model\GroupInterface
            joinTable:
                name: newsletter_newsletter_group
                joinColumns:
                    newsletter_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id

    lifecycleCallbacks: { }
