enhavo_newsletter_newsletter_show:
    path: /newsletter/show/{slug}
    methods: [GET]
    defaults:
        _expose: theme
        _endpoint:
            type: Enhavo\Bundle\NewsletterBundle\Endpoint\NewsletterEndpointType
            find_by: slug
