enhavo_newsletter_subscribe_activate:
    path: /newsletter/activate/{token}/{type}
    defaults:
        _expose: theme
        _endpoint:
            type: Enhavo\Bundle\NewsletterBundle\Endpoint\SubscriptionActivateEndpointType

enhavo_newsletter_subscribe_add:
    path: /newsletter/add/{type}
    methods: [POST]
    defaults:
        _expose: theme
        _endpoint:
            type: Enhavo\Bundle\NewsletterBundle\Endpoint\SubscriptionAddEndpointType

enhavo_newsletter_subscriber_unsubscribe:
    path: /newsletter/unsubscribe/{token}/{type}
    defaults:
        _expose: theme
        _endpoint:
            type: Enhavo\Bundle\NewsletterBundle\Endpoint\SubscriptionUnsubscribeEndpointType
