enhavo_newsletter_tracking_open:
    path: /newsletter/tracking/{token}
    methods: [GET]
    defaults:
        _expose: theme
        _endpoint:
            type: Enhavo\Bundle\NewsletterBundle\Endpoint\TrackingTrackEndpointType
