parameters:
    enhavo_newsletter.event.newsletter.class: enhavo\NewsletterBundle\EventListener\NewsletterBuilderSubscriber

services:
    enhavo_newsletter_newsletter_render:
        class: enhavo\NewsletterBundle\Twig\NewsletterRender
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }


    enhavo_newsletter_subscriber:
        class: %enhavo_newsletter.form.type.subscriber.class%
        tags:
            - { name: form.type }

    enhavo_newsletter_newsletter:
        class: %enhavo_newsletter.form.type.newsletter.class%
        tags:
            - { name: form.type }


    enhavo_newsletter.event.newsletter:
        class: %enhavo_newsletter.event.newsletter.class%
        arguments:
            - @service_container
            - %enhavo_newsletter.subscriber%
        tags:
            - { name: kernel.event_subscriber }
