parameters:
    enhavo_newsletter.event.newsletter.class: Enhavo\Bundle\NewsletterBundle\EventListener\NewsletterBuilderSubscriber

services:
    enhavo_newsletter_newsletter_render:
        class: Enhavo\Bundle\NewsletterBundle\Twig\NewsletterRender
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }


    enhavo_newsletter_subscriber:
        class: %enhavo_newsletter.form.type.subscriber.class%
        tags:
            - { name: form.type }

    enhavo_newsletter_newsletter:
        class: %enhavo_newsletter.form.type.newsletter.class%
        arguments:
            - @security.context
            - %enhavo_newsletter.model.newsletter.class%
        tags:
            - { name: form.type }


    enhavo_newsletter.event.newsletter:
        class: %enhavo_newsletter.event.newsletter.class%
        arguments:
            - @service_container
            - %enhavo_newsletter.subscriber%
        tags:
            - { name: kernel.event_subscriber }

    validator.unique.email_in_use_validator:
        class:  Enhavo\Bundle\NewsletterBundle\Validator\Constraints\SubscriberEmailInUseValidator
        arguments:
            - @doctrine.orm.default_entity_manager
            - @service_container
            - %enhavo_newsletter.subscriber%
        tags:
            - { name: validator.constraint_validator, alias: email_in_use }

    enhavo_newsletter.button.send:
        class: Enhavo\Bundle\NewsletterBundle\Button\SendButton
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.button }
