Enhavo\Bundle\NewsletterBundle\Entity\Subscriber:
    properties:
        email:
            - Email: ~
            - NotBlank: ~
    constraints:
        - Enhavo\Bundle\NewsletterBundle\Validator\Constraints\SubscriberExists: