services:
    enhavo_newsletter.button.send:
        class: Enhavo\Bundle\NewsletterBundle\Button\SendButton
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.button, alias: newsletter_send }

    enhavo_newsletter.button.view:
        class: Enhavo\Bundle\NewsletterBundle\Button\ViewButton
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.button, alias: newsletter_view }

    enhavo_newsletter.batch.send:
        class: Enhavo\Bundle\NewsletterBundle\Batch\SendBatch
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.batch, alias: newsletter_send }

    enhavo_newsletter.newsletter.manager:
        class: Enhavo\Bundle\NewsletterBundle\Newsletter\NewsletterManager
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@mailer'
          - '%enhavo_newsletter.newsletter.mail%'

    enhavo_newsletter_newsletter:
        class: '%enhavo_newsletter.form.type.newsletter.class%'
        arguments:
            - '%enhavo_newsletter.model.newsletter.class%'
        tags:
            - { name: form.type }

    Enhavo\Bundle\NewsletterBundle\Menu\NewsletterMenu:
        public: true
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo.menu, alias: newsletter_newsletter }

    enhavo_newsletter.extend_listener.newsletter:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\NewsletterBundle\Entity\Newsletter
            - '%enhavo_newsletter.model.newsletter.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }
