services:
#    Enhavo\Bundle\NewsletterBundle\Button\SendButton:
#        public: true
#        calls:
#            - [setContainer, ['@service_container']]
#        tags:
#            - { name: enhavo.button, alias: newsletter_send }
#
#    Enhavo\Bundle\NewsletterBundle\Button\ViewButton:
#        public: true
#        calls:
#            - [setContainer, ['@service_container']]
#        tags:
#            - { name: enhavo.button, alias: newsletter_view }

    Enhavo\Bundle\NewsletterBundle\Batch\SendType:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.batch, alias: newsletter_send }

    enhavo_newsletter.newsletter.manager:
        class: Enhavo\Bundle\NewsletterBundle\Newsletter\NewsletterManager
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@mailer'
          - '%enhavo_newsletter.newsletter.mail%'

    Enhavo\Bundle\NewsletterBundle\Form\Type\NewsletterType:
        arguments:
            - '%enhavo_newsletter.model.newsletter.class%'
        tags:
            - { name: form.type, alias: enhavo_newsletter_newsletter }

    Enhavo\Bundle\NewsletterBundle\Menu\NewsletterMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: newsletter_newsletter }

    enhavo_newsletter.extend_listener.newsletter:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\NewsletterBundle\Entity\Newsletter
            - '%enhavo_newsletter.model.newsletter.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }
