services:
    Enhavo\Bundle\NewsletterBundle\Batch\SendType:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.batch, alias: newsletter_send }

    Enhavo\Bundle\NewsletterBundle\Newsletter\NewsletterManager:
        public: true
        class: Enhavo\Bundle\NewsletterBundle\Newsletter\NewsletterManager
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@mailer'
          - '%enhavo_newsletter.newsletter.mail%'

    Enhavo\Bundle\NewsletterBundle\Form\Type\NewsletterType:
        arguments:
            - '%enhavo_newsletter.model.newsletter.class%'
        tags:
            - { name: form.type, alias: enhavo_newsletter_newsletter }

    Enhavo\Bundle\NewsletterBundle\Menu\NewsletterMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: newsletter_newsletter }

    enhavo_newsletter.extend_listener.newsletter:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\NewsletterBundle\Entity\Newsletter
            - '%enhavo_newsletter.model.newsletter.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    enhavo_newsletter.extend_listener.subscriber:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\NewsletterBundle\Entity\Subscriber
            - '%enhavo_newsletter.model.newsletter.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    enhavo_newsletter.extend_listener.group:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\NewsletterBundle\Entity\Group
            - '%enhavo_newsletter.model.newsletter.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }