services:
    Enhavo\Bundle\NewsletterBundle\Storage\Type\StorageType:
        public: true
        tags:
            - { name: enhavo_newsletter.storage }

    Enhavo\Bundle\NewsletterBundle\Storage\Type\LocalStorageType:
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@enhavo_newsletter.local_subscriber.repository'
            - '@enhavo_newsletter.group.repository'
            - '@enhavo_newsletter.local_subscriber.factory'
        tags:
            - { name: enhavo_newsletter.storage }

    Enhavo\Bundle\NewsletterBundle\Storage\Type\CleverReachStorageType:
        public: true
        arguments:
            - '@Enhavo\Bundle\NewsletterBundle\Client\CleverReachClient'
        tags:
            - { name: enhavo_newsletter.storage }

    Enhavo\Bundle\NewsletterBundle\Storage\Type\MailChimpStorageType:
        public: true
        arguments:
            - '@Enhavo\Bundle\NewsletterBundle\Client\MailChimpClient'
        tags:
            - { name: enhavo_newsletter.storage }

    Enhavo\Bundle\NewsletterBundle\Storage\Type\MailjetStorageType:
        public: true
        arguments:
            - '@Enhavo\Bundle\NewsletterBundle\Client\MailjetClient'
        tags:
            - { name: enhavo_newsletter.storage }
