enhavo_newsletter_newsletter_index:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/index
    methods: [GET]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:indexAction
        _sylius:
            viewer:
                apps:
                    - newsletter/NewsletterApp
                title: newsletter.label.newsletter
                translationDomain: EnhavoNewsletterBundle

enhavo_newsletter_newsletter_create:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/create
    methods: [GET,POST]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:createAction
        _sylius:
            viewer:
                translationDomain: EnhavoNewsletterBundle
                tabs:
                    main:
                        label: newsletter.label.newsletter
                        template: EnhavoNewsletterBundle:Newsletter:form.html.twig

enhavo_newsletter_newsletter_update:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:updateAction
        _sylius:
            viewer:
                translationDomain: EnhavoNewsletterBundle
                tabs:
                    main:
                        label: newsletter.label.newsletter
                        template: EnhavoNewsletterBundle:Newsletter:form.html.twig
                buttons:
                    send:
                        type: newsletter_send
                    view:
                        type: newsletter_view
                        route: enhavo_newsletter_newsletter_show

enhavo_newsletter_newsletter_table:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/table
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:tableAction
        _sylius:
            filters:
                title:
                    type: text
                    property: title
                    label: newsletter.label.title
                    translation_domain: EnhavoNewsletterBundle
            viewer:
                translationDomain: EnhavoNewsletterBundle
                batches:
                    actions:
                        delete:
                            label: table.batch.action.delete
                            confirm_message: table.batch.message.confirm.delete
                            translation_domain: EnhavoAppBundle
                            permission: ROLE_ENHAVO_NEWSLETTER_NEWSLETTER_DELETE
                            position: 0
                        send:
                            label: newsletter.batch.action.send
                            confirm_message: newsletter.batch.message.confirm.send
                            translation_domain: EnhavoNewsletterBundle
                            permission: ROLE_ENHAVO_NEWSLETTER_NEWSLETTER_SEND
                columns:
                    title:
                        type: text
                        label: newsletter.label.title
                        property: title
                        width: 10
                    sent:
                        type: boolean
                        label: newsletter.label.sent
                        property: sent
                        width: 2

enhavo_newsletter_newsletter_delete:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/delete/{id}
    methods: [POST]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:deleteAction

enhavo_newsletter_newsletter_batch:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/batch
    methods: [POST]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:batchAction
        _sylius:
            paginate: false
            criteria:
                id: $ids
            batches:
                delete:
                    type: delete
                newsletter_send:
                    type: newsletter_send

enhavo_newsletter_newsletter_preview:
    options:
        expose: true
    path: /admin/enhavo/newsletter/newsletter/preview
    methods: [POST]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:previewAction

enhavo_newsletter_newsletter_send:
    options:
        expose: true
    path: /admin/newsletter/newsletter/{id}/edit/send
    methods: [POST]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:sendEmailAction