enhavo_newsletter_newsletter_index:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/index
    methods: [GET]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:indexAction
        _sylius:
            viewer:
                label: newsletter.label.newsletter
                translation_domain: EnhavoNewsletterBundle

enhavo_newsletter_newsletter_create:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/create
    methods: [GET,POST]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:createAction
        _sylius:
            redirect: enhavo_newsletter_newsletter_update
            viewer:
                tabs:
                    main:
                        label: newsletter.label.newsletter
                        translation_domain: EnhavoNewsletterBundle
                        template: admin/resource/newsletter/main.html.twig
                    content:
                        label: newsletter.label.content
                        translation_domain: EnhavoNewsletterBundle
                        template: admin/resource/content/content.html.twig
                        full_width: true
                actions:
                    preview:
                        type: preview
                        route: enhavo_newsletter_newsletter_preview
                    test_mail:
                        type: newsletter_test_mail

enhavo_newsletter_newsletter_update:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:updateAction
        _sylius:
            serialization_groups: ['form']
            viewer:
                tabs:
                    main:
                        label: newsletter.label.newsletter
                        translation_domain: EnhavoNewsletterBundle
                        template: admin/resource/newsletter/main.html.twig
                    content:
                        label: newsletter.label.content
                        translation_domain: EnhavoNewsletterBundle
                        template: admin/resource/content/content.html.twig
                        full_width: true
                actions:
                    preview:
                        type: preview
                        route: enhavo_newsletter_newsletter_preview
                    test_mail:
                        type: newsletter_test_mail
                    send:
                        type: newsletter_send

enhavo_newsletter_newsletter_table:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/table
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:tableAction
        _sylius:
            filters:
                title:
                    type: text
                    property: title
                    label: newsletter.label.title
                    translation_domain: EnhavoNewsletterBundle
            viewer:
                translation_domain: EnhavoNewsletterBundle
                batches:
                    actions:
                        delete:
                            label: table.batch.action.delete
                            confirm_message: table.batch.message.confirm.delete
                            translation_domain: EnhavoAppBundle
                            permission: ROLE_ENHAVO_NEWSLETTER_NEWSLETTER_DELETE
                            position: 0
                        send:
                            label: newsletter.batch.action.send
                            confirm_message: newsletter.batch.message.confirm.send
                            translation_domain: EnhavoNewsletterBundle
                            permission: ROLE_ENHAVO_NEWSLETTER_NEWSLETTER_SEND
                columns:
                    title:
                        type: text
                        label: newsletter.label.title
                        property: title
                        width: 10
                    sent:
                        type: boolean
                        label: newsletter.label.sent
                        property: sent
                        width: 2

enhavo_newsletter_newsletter_delete:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/delete/{id}
    methods: [POST]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:deleteAction

enhavo_newsletter_newsletter_batch:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/batch
    methods: [POST]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:batchAction
        _sylius:
            paginate: false
            criteria:
                id: $ids
            batches:
                delete:
                    type: delete
                newsletter_send:
                    type: newsletter_send
                newsletter_send_test:
                    type: newsletter_send_test

enhavo_newsletter_newsletter_preview:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/preview
    methods: [GET]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:previewAction
        _sylius:
            viewer:

enhavo_newsletter_newsletter_resource_preview:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/resource/preview
    methods: [POST]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:previewResourceAction
        _sylius:
            viewer:
                strategy_options:
                    service: enhavo_newsletter.controller.newsletter:showResourceAction

enhavo_newsletter_newsletter_send:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/{id}/send
    methods: [POST]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:sendAction

enhavo_newsletter_newsletter_test:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/test
    methods: [POST]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:testAction

enhavo_newsletter_newsletter_test_form:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/test/form
    methods: [GET]
    controller: enhavo_app.controller.modal:formAction
    defaults:
        _config:
            form: Enhavo\Bundle\NewsletterBundle\Form\Type\NewsletterEmailType
