enhavo_resource:
    resources:
        enhavo_newsletter.group:
            classes:
                model: Enhavo\Bundle\NewsletterBundle\Entity\Group
                repository: Enhavo\Bundle\NewsletterBundle\Repository\GroupRepository
            label: group.label.group
            translation_domain: EnhavoNewsletterBundle
    grids:
        enhavo_newsletter.group:
            extends: enhavo_resource.grid
            resource: enhavo_newsletter.group
            actions:
                create:
                    type: create
                    permission: 'expr:permission("enhavo_newsletter.group", "create")'
                    route: 'expr:resolve_route("create", {api: false})'
            columns:
                name:
                    sortable: true
                    property: name
                    width: 8
                    label: group.label.name
                    type: text
                    translation_domain: EnhavoNewsletterBundle
                action:
                    width: 4
                    label: label.edit
                    translation_domain: EnhavoAppBundle
                    type: action
                    actions:
                        update:
                            type: update
                            route: enhavo_newsletter_admin_group_update
            batches:
                delete:
                    type: delete
    inputs:
        enhavo_newsletter.group:
            extends: enhavo_resource.input
            resource: enhavo_newsletter.group
            form: Enhavo\Bundle\NewsletterBundle\Form\Type\GroupType
            tabs:
                main:
                    type: form
                    label: group.label.group
                    translation_domain: EnhavoNewsletterBundle
                    arrangement: |
                        name
                        code
