enhavo_newsletter_admin_group_index:
    path: /group/index
    defaults:
        _expose: admin
        _vue:
            component: resource-index
            groups: admin
            meta:
                api: enhavo_newsletter_admin_api_group_index
        _endpoint:
            type: admin

enhavo_newsletter_admin_group_create:
    path: /group/create
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_newsletter_admin_api_group_create
        _endpoint:
            type: admin

enhavo_newsletter_admin_group_update:
    path: '/group/update/{id}'
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_newsletter_admin_api_group_update
        _endpoint:
            type: admin

