enhavo_newsletter_admin_local_subscriber_index:
    path: /local_subscriber/index
    defaults:
        _expose: admin
        _vue:
            component: resource-index
            groups: admin
            meta:
                api: enhavo_newsletter_admin_api_local_subscriber_index
        _endpoint:
            type: admin

enhavo_newsletter_admin_local_subscriber_create:
    path: /local_subscriber/create
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_newsletter_admin_api_local_subscriber_create
        _endpoint:
            type: admin

enhavo_newsletter_admin_local_subscriber_update:
    path: '/local_subscriber/update/{id}'
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_newsletter_admin_api_local_subscriber_update
        _endpoint:
            type: admin
