enhavo_newsletter_admin_newsletter_index:
    path: /newsletter/index
    defaults:
        _expose: admin
        _vue:
            component: resource-index
            groups: admin
            meta:
                api: enhavo_newsletter_admin_api_newsletter_index
        _endpoint:
            type: admin

enhavo_newsletter_admin_newsletter_create:
    path: /newsletter/create
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_newsletter_admin_api_newsletter_create
        _endpoint:
            type: admin

enhavo_newsletter_admin_newsletter_update:
    path: '/newsletter/update/{id}'
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_newsletter_admin_api_newsletter_update
        _endpoint:
            type: admin

enhavo_newsletter_admin_newsletter_stats:
    path: '/newsletter/stats/{id}'
    defaults:
        _expose: admin
        _vue:
            component: newsletter-stats
            groups: admin
        _endpoint:
            type: admin

enhavo_newsletter_newsletter_send:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/{id}/send
    defaults:
        _controller: enhavo_newsletter.controller.newsletter::sendAction

