enhavo_newsletter_admin_pending_subscriber_index:
    path: /pending_subscriber/index
    defaults:
        _expose: admin
        _vue:
            component: resource-index
            groups: admin
            meta:
                api: enhavo_newsletter_admin_api_pending_subscriber_index
        _endpoint:
            type: admin

enhavo_newsletter_admin_pending_subscriber_create:
    path: /pending_subscriber/create
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_newsletter_admin_api_pending_subscriber_create
        _endpoint:
            type: admin

enhavo_newsletter_admin_pending_subscriber_update:
    path: '/pending_subscriber/update/{id}'
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_newsletter_admin_api_pending_subscriber_update
        _endpoint:
            type: admin
