enhavo_assets:
    require_js:
        paths:
            newsletter:
                location: /bundles/enhavonewsletter/js

enhavo_newsletter:
    strategy:
        settings:
            notify:
                from: '%mailer_from%'
                admin_email: '%mailer_to%'
                sender_name: '%mailer_name%'
            accept:
                from: '%mailer_from%'
                admin_email: '%mailer_to%'
                sender_name: '%mailer_name%'
            double_opt_in:
                from: '%mailer_from%'
                admin_email: '%mailer_to%'
                sender_name: '%mailer_name%'
    forms:
        default:
            type: enhavo_newsletter_subscribe
            template: EnhavoNewsletterBundle:Subscriber:subscribe.html.twig

enhavo_app:
    roles:
        enhavo_newsletter_subscriber_index:
            role: ROLE_ENHAVO_NEWSLETTER_SUBSCRIBER_INDEX
            label: subscriber.role.label.index
            translationDomain: EnhavoNewsletterBundle
        enhavo_newsletter_subscriber_create:
            role: ROLE_ENHAVO_NEWSLETTER_SUBSCRIBER_CREATE
            label: subscriber.role.label.create
            translationDomain: EnhavoNewsletterBundle
        enhavo_newsletter_subscriber_update:
            role: ROLE_ENHAVO_NEWSLETTER_SUBSCRIBER_UPDATE
            label: subscriber.role.label.update
            translationDomain: EnhavoNewsletterBundle
        enhavo_newsletter_subscriber_delete:
            role: ROLE_ENHAVO_NEWSLETTER_SUBSCRIBER_DELETE
            label: subscriber.role.label.delete
            translationDomain: EnhavoNewsletterBundle

        enhavo_newsletter_newsletter_index:
            role: ROLE_ENHAVO_NEWSLETTER_NEWSLETTER_INDEX
            label: newsletter.role.label.index
            translationDomain: EnhavoNewsletterBundle
        enhavo_newsletter_newsletter_create:
            role: ROLE_ENHAVO_NEWSLETTER_NEWSLETTER_CREATE
            label: newsletter.role.label.create
            translationDomain: EnhavoNewsletterBundle
        enhavo_newsletter_newsletter_update:
            role: ROLE_ENHAVO_NEWSLETTER_NEWSLETTER_UPDATE
            label: newsletter.role.label.update
            translationDomain: EnhavoNewsletterBundle
        enhavo_newsletter_newsletter_delete:
            role: ROLE_ENHAVO_NEWSLETTER_NEWSLETTER_DELETE
            label: newsletter.role.label.delete
            translationDomain: EnhavoNewsletterBundle
        enhavo_newsletter_newsletter_send:
            role: ROLE_ENHAVO_NEWSLETTER_NEWSLETTER_SEND
            label: newsletter.role.label.send
            translationDomain: EnhavoNewsletterBundle
        enhavo_newsletter_newsletter_view:
            role: ROLE_ENHAVO_NEWSLETTER_NEWSLETTER_VIEW
            label: newsletter.role.label.view
            translationDomain: EnhavoNewsletterBundle


enhavo_grid:
    render:
        sets:
            newsletter:
                picture: EnhavoNewsletterBundle:Theme\GridItem:picture.html.twig
                picture_picture: EnhavoNewsletterBundle:Theme\GridItem:picture_picture.html.twig
                three_picture: EnhavoNewsletterBundle:Theme\GridItem:three_picture.html.twig
                gallery: EnhavoNewsletterBundle:Theme\GridItem:gallery.html.twig
                text: EnhavoNewsletterBundle:Theme\GridItem:text.html.twig
                text_picture: EnhavoNewsletterBundle:Theme\GridItem:text_picture.html.twig
                text_text: EnhavoNewsletterBundle:Theme\GridItem:text_text.html.twig
                cite_text: EnhavoNewsletterBundle:Theme\GridItem:cite_text.html.twig
                download: EnhavoNewsletterBundle:Theme\GridItem:download.html.twig
                video: EnhavoNewsletterBundle:Theme\GridItem:video.html.twig

enhavo_routing:
    classes:
        Enhavo\Bundle\NewsletterBundle\Entity\Newsletter:
            router:
                default:
                    type: slug
                admin:
                    type: id
                    route: enhavo_newsletter_newsletter_update
            generators:
                slug:
                    type: slug
                    property: title