enhavo_assets:
    require_js:
        paths:
            newsletter:
                location: /bundles/enhavonewsletter/js

enhavo_newsletter:
    strategy:
        settings:
            notify:
                from: '%mailer_from%'
                admin_email: '%mailer_to%'
            accept:
                from: '%mailer_from%'
                admin_email: '%mailer_to%'
            double_opt_in:
                from: '%mailer_from%'
                admin_email: '%mailer_to%'
    forms:
        default:
            type: enhavo_newsletter_subscribe
            template: EnhavoNewsletterBundle:Subscriber:subscribe.html.twig
