enhavo_assets:
    require_js:
        paths:
            newsletter:
                location: /bundles/enhavonewsletter/js

enhavo_newsletter:
    forms:
        default:
            type: enhavo_newsletter_subscribe
            template: EnhavoNewsletterBundle:Subscriber:subscribe.html.twig