enhavo_newsletter_newsletter_index:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/index
    methods: [GET]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:indexAction
        _sylius:
            template: EnhavoAppBundle:Resource:index.html.twig
        _viewer:

enhavo_newsletter_newsletter_create:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/create
    methods: [GET,POST]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:createAction
        _sylius:
            template: EnhavoAppBundle:Resource:create.html.twig
        _viewer:

enhavo_newsletter_newsletter_update:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:updateAction
        _sylius:
            template: EnhavoAppBundle:Resource:update.html.twig
        _viewer:

enhavo_newsletter_newsletter_table:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/table/{page}
    methods: [GET]
    defaults:
        page: 1
        _controller: enhavo_newsletter.controller.newsletter:tableAction
        _sylius:
            template: EnhavoAppBundle:Resource:table.html.twig
        _viewer:
            table:
                columns:
                    id:
                        label: ID
                        property: id
                    title:
                        label: title
                        property: title

enhavo_newsletter_newsletter_delete:
    options:
        expose: true
    path: /enhavo/newsletter/newsletter/delete/{id}
    methods: [POST]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:deleteAction

enhavo_newsletter_newsletter_preview:
    options:
        expose: true
    path: /admin/enhavo/newsletter/newsletter/preview
    methods: [POST]
    defaults:
        _controller: enhavo_newsletter.controller.newsletter:previewAction