enhavo_newsletter_activation:
    pattern: /newsletter/add/{code}
    defaults: { _controller: EnhavoNewsletterBundle:Subscriber:activation }

enhavo_newsletter_create:
    path: /newsletter/new
    methods: [GET, POST]
    options:
        expose: true
    defaults:
        _controller: enhavo_newsletter.controller.subscriber:createAction
        _admin: enhavo_newsletter.admin.subscriber

enhavo_newsletter_send_email:
    pattern: /admin/newsletter/newsletter/{newsletterId}/edit/send
    defaults: { _controller: EnhavoNewsletterBundle:Subscriber:sendEmail }