enhavo_newsletter_subscriber_activation:
    pattern: /newsletter/add/{code}
    defaults: { _controller: EnhavoNewsletterBundle:Subscriber:activation }

enhavo_newsletter_subscriber_create:
    path: /newsletter/new
    methods: [GET, POST]
    options:
        expose: true
    defaults:
        _controller: enhavo_newsletter.controller.subscriber:createAction
        _admin: enhavo_newsletter.admin.subscriber
